[package]
authors = ["Andrew Korzhuev <korzhuev@andrusha.me>"]
categories = ["api-bindings", "database"]
description = "Snowflake API bindings"
documentation = "http://docs.rs/sqlite-api/"
edition = "2024"
keywords = ["api", "database", "snowflake"]
license = "Apache-2.0"
name = "snowflake-api"
readme = "README.md"
repository = "https://github.com/mycelial/snowflake-rs"
version = "0.10.0"

[features]
all = ["cert-auth", "polars"]
cert-auth = ["dep:snowflake-jwt"]
default = ["cert-auth"]
# support for conversion of arrow and json payloads to dataframes
polars = ["dep:polars-core", "dep:polars-io"]

[dependencies]
arrow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
reqwest-retry = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
snowflake-jwt = { workspace = true, optional = true }
thiserror = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

# polars-support
polars-core = { workspace = true, optional = true }
polars-io = {workspace = true, optional = true }

# put request support
glob = { workspace = true }
object_store = { workspace = true }
tokio = { workspace = true }
flate2 = { workspace = true }

